remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Mehar Kaif
description: "Innovating with AI. Developing with passion."
logo: /mehar-headshot.png
#show_downloads: true
theme: jekyll-theme-minimal
